// ELEC2645 PWM Library Example
// This example demonstrates how to use the pwm.h library with Timer 4 PWM

// STM32 HAL headers (auto-generated by STM32CubeMX)
#include "main.h"
#include "tim.h"       // Timer 4 for PWM LED control
#include "usart.h"     // For serial output
#include "gpio.h"      // GPIO control

// AUTO-GENERATED STM32 FUNCTION PROTOTYPES - DO NOT EDIT
void SystemClock_Config(void);
void PeriphCommonClock_Config(void);

// PWM library
#include "PWM.h"
#include "LCD.h"  // For LCD demonstration (optional)


#include <stdint.h>
#include <stdio.h>

// ===== PWM CONFIGURATION =====
// Configure PWM to use TIM4 Channel 1 (current hardware setup)
PWM_cfg_t pwm_cfg = {
    .htim = &htim4,
    .channel = TIM_CHANNEL_1,
    .tick_freq_hz = 1000000,  // 1MHz timer clock (prescaler = 79 with 80MHz input)
    .min_freq_hz = 10,
    .max_freq_hz = 50000,
    .setup_done = 0
};

// ===== UTILITY FUNCTIONS =====

/**
 * @brief Redirect printf to UART for debugging
 */
int _write(int file, char *ptr, int len) {
    HAL_UART_Transmit(&huart2, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}


/**
 * @brief Example 1: Test different PWM frequencies (LED will flash at different rates)
 */
static void example_1_different_frequencies(void)
{
    printf("Example 1: Testing different PWM frequencies at 50%% duty...\n");
    
    printf("  10 Hz - LED flashing visible\n");
    PWM_Set(&pwm_cfg, 10, 50);
    HAL_Delay(2000);
    
    printf("  25 Hz - LED flashing faster\n");
    PWM_Set(&pwm_cfg, 25, 50);
    HAL_Delay(2000);
    
    printf("  1000 Hz - Smooth brightness (1kHz)\n");
    PWM_Set(&pwm_cfg, 1000, 50);
    HAL_Delay(2000);
    
    printf("  5000 Hz - Very smooth (5kHz)\n");
    PWM_Set(&pwm_cfg, 5000, 50);
    HAL_Delay(2000);
    
    PWM_Off(&pwm_cfg);
    HAL_Delay(500);
}

/**
 * @brief Example 2: Test different brightness levels (duty cycle)
 */
static void example_2_brightness_control(void)
{
    printf("\nExample 2: Testing brightness control at 1kHz...\n");
    
    // Set frequency once
    PWM_SetFreq(&pwm_cfg, 1000);

    // Fade up from 0% to 100%
    printf("  Fading up (0%% to 100%%)...\n");
    for (uint8_t brightness = 0; brightness <= 100; brightness += 5) {
        printf("    Brightness: %u%%\n", brightness);
        PWM_SetDuty(&pwm_cfg, brightness);
        HAL_Delay(200);
    }
    
    HAL_Delay(500);
    
    // Fade down from 100% to 0%
    printf("  Fading down (100%% to 0%%)...\n");
    for (int brightness = 100; brightness >= 0; brightness -= 5) {
        printf("    Brightness: %d%%\n", brightness);
        PWM_SetDuty(&pwm_cfg, (uint8_t)brightness);
        HAL_Delay(200);
    }
    
    PWM_Off(&pwm_cfg);
    HAL_Delay(500);
}

/**
 * @brief Example 3: Smooth breathing effect
 */
static void example_3_breathing_effect(void)
{
    printf("\nExample 3: LED breathing effect...\n");
    
    // Set frequency to 1kHz for smooth LED control
    PWM_SetFreq(&pwm_cfg, 1000);
    
    for (int cycle = 0; cycle < 3; cycle++) {
        printf("  Breathing cycle %d...\n", cycle + 1);
        
        // Fade in
        for (uint8_t brightness = 0; brightness <= 100; brightness++) {
            PWM_SetDuty(&pwm_cfg, brightness);
            HAL_Delay(15);
        }
        
        // Fade out
        for (int brightness = 100; brightness >= 0; brightness--) {
            PWM_SetDuty(&pwm_cfg, (uint8_t)brightness);
            HAL_Delay(15);
        }
    }
    
    PWM_Off(&pwm_cfg);
    printf("  Breathing effect complete!\n");
}


/**
  * @brief  The application entry point - PWM LED demonstration
  * @retval int
  */
int main(void)
{
    /* MCU Configuration */
    HAL_Init();
    SystemClock_Config();
    PeriphCommonClock_Config();

    /* Initialize peripherals */
    MX_GPIO_Init();
    MX_USART2_UART_Init();


    ST7789V2_cfg_t cfg0 = {
    .setup_done = 0,
    .spi = SPI2,
    .RST = {.port = GPIOB, .pin = GPIO_PIN_2},
    .BL = {.port = GPIOB, .pin = GPIO_PIN_1},
    .DC = {.port = GPIOB, .pin = GPIO_PIN_11},
    .CS = {.port = GPIOB, .pin = GPIO_PIN_12},
    .MOSI = {.port = GPIOB, .pin = GPIO_PIN_15},
    .SCLK = {.port = GPIOB, .pin = GPIO_PIN_13},
    .dma = {.instance = DMA1, .channel = DMA1_Channel5}
  };

    // Initialize LCD first (this sets up GPIOB pins)
    LCD_init(&cfg0);
  
    // Initialize TIM4 AFTER LCD to avoid GPIO conflict on PB6
    MX_TIM4_Init();
  
    // Then initialize PWM library
    PWM_Init(&pwm_cfg);

    // make screen black (0 in palette set in LCD.h)
    LCD_Fill_Buffer(0);

    LCD_Refresh(&cfg0);

    LCD_printString("PWM LED",  0, 10, 1, 5);
    LCD_Refresh(&cfg0);
    HAL_Delay(200); // delay by 200 ms to allow time to see the text 
    LCD_printString("Library",  0, 70, 1, 5);
    LCD_Refresh(&cfg0);
    HAL_Delay(200);
    LCD_printString("Test",  0, 140, 1, 5);
    LCD_Refresh(&cfg0);

    printf("\n=== ELEC2645 PWM Library Example ===\n");
    printf("This example demonstrates the pwm.h library\n");
    printf("The LED uses Timer 4 PWM on Channel 1\n\n");

    // Give a moment for the user to see the startup message
    HAL_Delay(1000);

    // ===== RUN EXAMPLES =====
    // Comment out any example below to skip it
    
    example_1_different_frequencies();   // Example 1: Different PWM frequencies
    example_2_brightness_control();      // Example 2: Brightness control (duty cycle)
    example_3_breathing_effect();        // Example 3: Smooth breathing LED

    printf("\n=== PWM demonstration complete! ===\n");
    printf("LED is now OFF. You can uncomment the loop below\n");
    printf("to continuously repeat the examples.\n\n");

    /**
     * ===== MAIN LOOP =====
     * 
     * The examples above run once at startup.
     * Uncomment the while loop below to repeat the demonstration continuously.
     * 
     * For your own projects, you can:
     * - Call PWM_Set(&pwm_cfg, freq, duty) to set frequency and brightness
     * - Call PWM_SetFreq(&pwm_cfg, freq) to change frequency only
     * - Call PWM_SetDuty(&pwm_cfg, duty) to change brightness only
     * - Call PWM_Off(&pwm_cfg) to turn off the LED
     * - Check PWM_IsRunning(&pwm_cfg) to see if PWM is active
     */
    while (1)
    {
        // Examples complete - LED is OFF
        // You can add your own code here
        
        HAL_Delay(100);
        
        // Uncomment below to repeat the demonstration every 10 seconds
        /*
        HAL_Delay(10000);
        printf("\n--- Repeating demonstration ---\n");
        example_3_breathing_effect();
        */
    }
}


// ==== AUTO-GENERATED STM32 FUNCTIONS ====
// DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING! 


/**
  * @brief System Clock Configuration
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  if (HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = 1;
  RCC_OscInitStruct.PLL.PLLN = 10;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV7;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_4) != HAL_OK)
  {
    Error_Handler();
  }
}

/**
  * @brief Peripherals Common Clock Configuration
  * @retval None
  */
void PeriphCommonClock_Config(void)
{
  RCC_PeriphCLKInitTypeDef PeriphClkInit = {0};

  /** Initializes the peripherals clock
  */
  PeriphClkInit.PeriphClockSelection = RCC_PERIPHCLK_RNG|RCC_PERIPHCLK_ADC;
  PeriphClkInit.AdcClockSelection = RCC_ADCCLKSOURCE_PLLSAI1;
  PeriphClkInit.RngClockSelection = RCC_RNGCLKSOURCE_PLLSAI1;
  PeriphClkInit.PLLSAI1.PLLSAI1Source = RCC_PLLSOURCE_HSI;
  PeriphClkInit.PLLSAI1.PLLSAI1M = 1;
  PeriphClkInit.PLLSAI1.PLLSAI1N = 8;
  PeriphClkInit.PLLSAI1.PLLSAI1P = RCC_PLLP_DIV7;
  PeriphClkInit.PLLSAI1.PLLSAI1Q = RCC_PLLQ_DIV4;
  PeriphClkInit.PLLSAI1.PLLSAI1R = RCC_PLLR_DIV2;
  PeriphClkInit.PLLSAI1.PLLSAI1ClockOut = RCC_PLLSAI1_48M2CLK|RCC_PLLSAI1_ADC1CLK;
  if (HAL_RCCEx_PeriphCLKConfig(&PeriphClkInit) != HAL_OK)
  {
    Error_Handler();
  }
}



/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  /* User can add his own implementation to report the HAL error return state */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
#ifdef USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
